### PR TITLE
Add deb support for control.tar files

### LINKED ISSUE #632: Aptly cannot use deb packages which have control.tar
## Detailed Description
Aptly cannot handle packages which have `control.tar` control files instead of `control.tar.gz`.

## Context
Most gzip implementations are non-deterministic. Since control.tar is supported buy dpkg it should also be supported by aptly.

## Possible Implementation
```diff
diff --git a/deb/deb.go b/deb/deb.go
index 26db3a1..f5f0c40 100644
--- a/deb/deb.go
+++ b/deb/deb.go
@@ -44,12 +44,16 @@ func GetControlFileFromDeb(packageFile string) (Stanza, error) {
                        return nil, fmt.Errorf("unable to read .deb archive %s: %s", packageFile, err)
                }
 
-               if header.Name == "control.tar.gz" {
-                       ungzip, err := gzip.NewReader(library)
-                       if err != nil {
-                               return nil, fmt.Errorf("unable to ungzip control file from %s. Error: %s", packageFile, err)
+               if strings.HasPrefix(header.Name, "control.tar") {
+                       if strings.HasSuffix(header.Name, ".gz") {
+                               ungzip, err := gzip.NewReader(library)
+                               if err != nil {
+                                       return nil, fmt.Errorf("unable to ungzip control file from %s. Error: %s", packageFile, err)
+                               }
+                               defer ungzip.Close()
+                       } else {
+                               ungzip := library
                        }
-                       defer ungzip.Close()
 
                        untar := tar.NewReader(ungzip)
                        for {
```

### PR DESCRIPTION
**Pull request by rlguarino**
Add support for control archives with no compression.

Resolves #632

## Checklist

- [x] unit-test added (if change is algorithm)
- [ ] functional test added/updated (if change is functional)
- [x] man page updated (if applicable)
- [x] bash completion updated (if applicable)
- [x] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by smira** [comment]
@rlguarino I think adding new package to `system/files/` breaks too many system tests which try to add whole `system/files/` directory to repository.

**Comment by rlguarino** [comment]
@smira  what do you think is the best course of action here? Should we drop the tests, create a new `sysmte/files2` folder, or fix all of the existing system tests?

**Comment by smira** [comment]
@rlguarino I would probably try to put it some other directory - I think that's the easiest fix.

**Comment by smira** [comment]
Thanks, got merged as #658

**Pull request closed without merging**
