### PR TITLE
Add swift backend for repository publishing

### PR DESCRIPTION
**Pull request by sbadia**
This pull request implements the Openstack Swift backend for aptly in the model of the existing S3 backend.

The Python test suite needs a real Swift server.
The Go test suite uses a fake server written in Go (in https://github.com/lebauce/swift repository which is really just https://github.com/ncw/swift with the fake server). A pull request is on the way so that we can fallback to upstream once it's merged.

Close: #164

### CODE REVIEW

**Comment by smira** [comment]
@sbadia thanks for your pull request!

It's my first experience with Swift. Could you please help me  to make system tests run?

What I did:

```
pip install python-keystoneclient python-swiftclient
docker run -d -p 8080:8080 serverascode/swift-onlyone
export OS_AUTH_URL=http://127.0.0.1:8181/v2.0/
export OS_USERNAME=user_test
export OS_PASSWORD=tester
export OS_TENANT_NAME=testing
```

(Port 8080 is proxied to 127.0.0.1:8181 in my setup)

I've tried different `OS_AUTH_URL`s, but nothing helped:

`swiftclient.exceptions.ClientException: Authorization Failure. Authorization Failed: Bad Request (HTTP 400)`

In container logs I see:

```
Feb  7 16:53:54 22e603131f5f account-server: 127.0.0.1 - - [07/Feb/2015:16:53:54 +0000] "HEAD /sdb1/95/tokens" 404 - "tx86f4fa33e10d4100a98ed-0054d64322" "HEAD http://127.0.0.1:8181/v1/tokens" "proxy-server 92" 0.0002 ""
Feb  7 16:53:54 22e603131f5f proxy-server: - - 07/Feb/2015/16/53/54 HEAD /v1/tokens HTTP/1.0 204 - Swift - - - - tx86f4fa33e10d4100a98ed-0054d64322 - 0.0025 GET_INFO - 1423328034.288862944 1423328034.291368961
Feb  7 16:53:54 22e603131f5f proxy-server: 10.0.2.2 10.0.2.2 07/Feb/2015/16/53/54 POST /auth/tokens HTTP/1.0 400 - python-keystoneclient - - 137 - tx86f4fa33e10d4100a98ed-0054d64322 - 0.0038 - - 1423328034.288005114 1423328034.291802883
Feb  7 16:53:54 22e603131f5f proxy-server: 10.0.2.2 10.0.2.2 07/Feb/2015/16/53/54 POST /auth/tokens HTTP/1.0 400 - python-keystoneclient - - 137 - txae4adecb46c44ec595ea7-0054d64322 - 0.0008 - - 1423328034.301757097 1423328034.302517891
```

**Comment by lebauce** [comment]
The test Swift server has been merged upstream. I pushed a commit to use it instead of my fork :
https://github.com/lebauce/aptly/commit/355a98b51ff883a7495976c9373dd40ff41ed1ef

**Comment by sbadia** [comment]
Hi @smira,
It seems that the docker container changes the password at every boot, but you [can't disable it for the moment](https://github.com/ccollicutt/docker-swift-onlyone/commit/c9f5e41b745eee18e7ddc807481bc9729d8cdac0) :-)
@lebauce just submitted a [comment on docker registry](https://registry.hub.docker.com/u/serverascode/swift-onlyone/) in order to have a working container.
And we just added support for TempUrl support (for v1 authentication, without Keystone):
* https://github.com/sbadia/aptly/commits/sbadia-swift

You can cherry pick this three commits.
* https://github.com/sbadia/aptly/commit/355a98b51ff883a7495976c9373dd40ff41ed1ef
* https://github.com/sbadia/aptly/commit/2a08c6fcc2f315b0b8b34e427e829ca8dafa615e
* https://github.com/sbadia/aptly/commit/50f05d13462ced44936d5a85044f2bb10625296a


Thanks in advance!

**Comment by smira** [comment]
@sbadia thanks for your help!

I got myself much further, but I'm still stuck:

In docker container I get this error:

```
Feb 11 19:15:00 a5f7b31d554e object-server: 127.0.0.1 - - [11/Feb/2015:19:15:00 +0000] "PUT /sdb1/65/AUTH_test/aptly-sys-test-fc0e2a5e-4ee4-46f8-923e-910a2868da19/pool/main/b/boost-defaults/libboost-program-options-dev_1.49.0.1_i386.deb" 500 944 "PUT http://127.0.0.1:8181/v1/AUTH_test/aptly-sys-test-fc0e2a5e-4ee4-46f8-923e-910a2868da19/pool/main/b/boost-defaults/libboost-program-options-dev_1.49.0.1_i386.deb" "txd226a9b5ac724f18921d9-0054dbaa34" "proxy-server 93" 0.0116
Feb 11 19:15:00 a5f7b31d554e proxy-server: ERROR 500 Traceback (most recent call last):#012  File "/usr/lib/python2.7/dist-packages/swift/obj/server.py", line 671, in __call__#012    res = method(req)#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2217, in wrapped#012    return func(*a, **kw)#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 837, in _timing_stats#012    resp = func(ctrl, *args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/swift/obj/server.py", line 452, in PUT#012    writer.put(metadata)#012  File "/usr/lib/python2.7/dist-packages/swift/obj/diskfile.py", line 742, in put#012    self._finalize_put, metadata, target_path)#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2536, in force_run_in_thread#012    return self._run_in_eventlet_tpool(func, *args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2519, in _run_in_eventlet_tpool#012    raise result#012IOError: [Errno 95] Operation not supported#012 From Object Server re: /v1/AUTH_test/aptly-sys-test-fc0e2a5e-4ee4-46f8-923e-910a2868da19/pool/main/b/boost-defaults/libboost-program-options-dev_1.49.0.1_i386.deb 127.0.0.1:6010/sdb1 (txn: txd226a9b5ac724f18921d9-0054dbaa34) (client_ip: 10.0.2.2)
Feb 11 19:15:00 a5f7b31d554e proxy-server: Object PUT returning 503 for [500] (txn: txd226a9b5ac724f18921d9-0054dbaa34) (client_ip: 10.0.2.2)
```

While aptly from tests complains like that:

```
ERROR: unable to publish: unable to process packages: error uploading /Users/smira/.aptly/pool/00/35/libboost-program-options-dev_1.49.0.1_i386.deb to Swift: http://127.0.0.1:8181/v1/AUTH_test:aptly-sys-test-fc0e2a5e-4ee4-46f8-923e-910a2868da19/: HTTP Error: 503: 503 Internal Server Error
```

**Comment by smira** [comment]
I'm just doing:

```
. .swift.sh
system/run.py Swift*
```

**Comment by smira** [comment]
Probably this error is also related:

```
Feb 11 19:24:51 a5f7b31d554e container-sync: UNCAUGHT EXCEPTION#012Traceback (most recent call last):#012  File "/usr/bin/swift-container-sync", line 23, in <module>#012    run_daemon(ContainerSync, conf_file, **options)#012  File "/usr/lib/python2.7/dist-packages/swift/common/daemon.py", line 110, in run_daemon#012    klass(conf).run(once=once, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/swift/common/daemon.py", line 57, in run#012    self.run_forever(**kwargs)#012  File "/usr/lib/python2.7/dist-packages/swift/container/sync.py", line 173, in run_forever#012    for path, device, partition in all_locs:#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 1721, in audit_location_generator#012    partitions = listdir(datadir_path)#012  File "/usr/lib/python2.7/dist-packages/swift/common/utils.py", line 2160, in listdir#012    return os.listdir(path)#012OSError: [Errno 20] Not a directory: '/srv/account.ring.gz/containers'
```

**Comment by lebauce** [comment]
It's strange. It works on my setup with the very same commands :

`$ . .swift.sh`
`$ system/run.py Swift*`
`t06_publish:SwiftPublish1Test... OK`
`t06_publish:SwiftPublish2Test... OK`
`t06_publish:SwiftPublish4Test... OK`
`t06_publish:SwiftPublish5Test... OK`
`TESTS: 4 SUCCESS: 4 FAIL: 0 SKIP: 1`

**Comment by smira** [comment]
I'll try to dig further into that for the release 0.9.5 (I hope it would be shortly after 0.9).

**Comment by smira** [comment]
I've finally managed to get working using Orbit from Brightbox as test environment.

So some final touches and I'll merge it. Thanks @sbadia, @lebauce and John Leach!

**Comment by smira** [comment]
Merged to `master`, nightly build `aptly_0.9~dev+217+ge5d646c`

**Comment by smira** [comment]
@sbadia I've compiled some docs from man page: http://beta.aptly.info/doc/feature/swift/

Please feel free to correct mistakes I've made or expand it (e.g. how to consume published repositories from apt, recommended configuration, possible mistakes, etc.): https://github.com/aptly-dev/aptly-dev.github.io/blob/next-9/content/doc/feature/swift.md

**Pull request merged**
