### PR TITLE
Identity v3 support for Swift

### PR DESCRIPTION
**Pull request by einarf**
ncw/swift was bumped to latest version

### CODE REVIEW

**Comment by einarf** [comment]
There's probably some documentation somewhere that needs updating if this gets merged. Now sure where. There is a `man` folder as well, but is that maybe just generated?

### Quick explanation of the changes

Version 3 authentication uses domains. Each domain can have several projects. The user will have to authenticate towards a domain and tell what domain the project belongs to (scoping).

- `Domain` or `DomainID` is the domain the user is authenticating towards.
- `TenantDomain` or `TenantDomainID` is where the tenant/project is located. (scoping)

This change was tested on the Zetta.IO public cloud and should work on any other setup that uses standard 3v authentication.

**Comment by einarf** [comment]
@smira or anyone around to take quick look? This is just bumping library version and passing in a few extra arguments.

**Comment by smira** [comment]
@einarf thanks for your PR

Docs are here: https://github.com/aptly-dev/aptly-dev.github.io

**Comment by einarf** [comment]
@smira docs ready: aptly-dev/aptly-dev.github.io#22

**Comment by smira** [comment]
thanks!

**Pull request merged**
