### PR TITLE
Try to reduce build duration

### PR DESCRIPTION
**Pull request by AlekSi**
Build duration increased since a switch to Trusty: https://travis-ci.org/smira/aptly/builds Let's see if this will be faster.

### CODE REVIEW

**Comment by AlekSi** [comment]
Hm, for some reason `exclude` doesn't work there. 😕

**Comment by smira** [comment]
I think I fixed the build in another PR

**Comment by AlekSi** [comment]
Seems to be faster now:
https://travis-ci.org/smira/aptly/builds/258692136
https://travis-ci.org/smira/aptly/builds/259485951

**Comment by smira** [comment]
Yep, thanks 👍

**Pull request merged**
